server:
    servlet:
        context-path: /api
custom:
    server:
        url: http://localhost:8080

springdoc:
    swagger-ui:
        path: /swagger-ui.html

spring:
    datasource:
        url: jdbc:h2:mem:sampledb
        driverClassName: org.h2.Driver
        username: sa
        password: password

    jpa:
        hibernate:
            ddl-auto: update

    h2:
        console:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include: '*'
